export const governanceTexts = {
  general: {
    notAvailable: '-',
    empty: '—',
    noData: 'Sem dados disponíveis no momento.',
    alertTitle: 'Aviso',
    errorTitle: 'Erro',
    attentionTitle: 'Atenção',
    retry: 'Tentar novamente',
    back: 'Voltar',
    cancel: 'Cancelar',
    close: 'Fechar',
    update: 'Atualizar',
    save: 'Salvar',
    all: 'Todos',
    clearFilters: 'Limpar filtros',
    refreshList: 'Atualizar lista',
    page: (current: number, total: number) => `Página ${current} de ${total}`,
    previous: 'Anterior',
    next: 'Próxima',
  },
  accessibility: {
    close: 'Fechar',
    more: 'Mais',
    morePages: 'Mais páginas',
    previous: 'Anterior',
    next: 'Próxima',
    previousSlide: 'Slide anterior',
    nextSlide: 'Próximo slide',
    breadcrumb: 'Trilha de navegação',
    toggleSidebar: 'Alternar menu lateral',
    pagination: 'Paginação',
  },
  severity: {
    labels: {
      INFO: 'Informativo',
      WARN: 'Alerta',
      ERROR: 'Crítico',
    },
    shortLabels: {
      INFO: 'Informativo',
      WARN: 'Alerta',
      ERROR: 'Crítico',
    },
    tooltip: 'Impacto no suporte, operação ou cliente final',
  },
  status: {
    labels: {
      OPEN: 'Aguardando ação',
      ASSIGNED: 'Com responsável',
      IN_PROGRESS: 'Em andamento',
      RESOLVED: 'Resolvido',
      IGNORED: 'Descartado',
    },
  },
  sla: {
    noDueDate: 'Sem prazo',
    overdue: 'Atrasado',
    dueToday: 'Vence hoje',
    onTrack: 'No prazo',
  },
  issueTypes: {
    REVIEW_REQUIRED: 'Revisão necessária',
    NOT_AI_READY: 'Não pronto para IA',
    DUPLICATE_CONTENT: 'Conteúdo duplicado',
    INCOMPLETE_CONTENT: 'Conteúdo incompleto',
  },
  dashboard: {
    title: 'Painel de governança',
    description: 'Decisões rápidas sobre riscos e prioridades de governança',
    cards: {
      openIssues: 'Issues abertas',
      overdueIssues: 'Issues vencidas',
      unassignedIssues: 'Sem responsável',
      needsOpenRecurring: 'Needs abertas/recorrentes',
      cta: 'Clique para aplicar filtro',
    },
    charts: {
      issuesBySystem: 'Issues por sistema',
      issuesByStatus: 'Issues por status',
      emptyTitle: 'Sem dados para gráfico',
      emptyDescription: 'Assim que houver dados, a distribuição aparecerá aqui.',
    },
    managerOnly: {
      title: 'Painel completo disponível para gestores',
      description: 'Aqui você acompanha apenas suas pendências. Para visão total, acesse com perfil de gestor.',
      cta: 'Ir para minhas issues',
    },
    empty: {
      title: 'Sem dados de governança',
      description: 'Conecte a base de dados para preencher o painel com indicadores.',
    },
    errors: {
      loadDashboard: 'Erro ao carregar o painel de governança',
      invalidMetrics: 'Algumas métricas vieram inválidas e foram ajustadas para 0.',
    },
  },
  articles: {
    title: 'Manuais',
    description: 'Gerencie os artigos da base de conhecimento',
    searchPlaceholder: 'Buscar manuais...',
    emptyTitle: 'Nenhum manual encontrado',
    emptyDescription: 'Tente ajustar os filtros de busca',
    loadError: 'Erro ao carregar manuais',
    loadErrorCard: 'Erro ao carregar dados',
    table: {
      title: 'Título',
      system: 'Sistema',
      status: 'Situação',
      updatedAt: 'Atualizado',
      actions: 'Ações',
    },
    actionOpen: 'Abrir manual',
    titleUnavailable: 'Título não disponível',
  },
  sync: {
    title: 'Sincronização',
    description: 'Histórico de sincronizações com Movidesk',
    runAction: 'Executar sincronização',
    runStartedTitle: 'Sincronização iniciada',
    runStartedDescription: 'Executando sincronização manual...',
    runSuccessTitle: 'Sincronização concluída',
    runSuccessDescription: 'Sincronização concluída com sucesso',
    runError: 'Erro ao executar sincronização',
    loadError: 'Erro ao carregar histórico de sincronizações',
    emptyTitle: 'Nenhuma sincronização encontrada',
    emptyDescription: 'Ainda não há histórico de sincronizações. Execute uma sincronização manual.',
    table: {
      startedAt: 'Início',
      status: 'Situação',
      mode: 'Modo',
      processed: 'Processados',
      note: 'Nota',
    },
    noteFallback: 'Sem observação',
    manualNote: 'Sincronização manual',
  },
  settings: {
    title: 'Configurações',
    description: 'Configurações de sincronização automática',
    syncTitle: 'Sincronização automática',
    syncDescription: 'Ativar sincronização automática',
    modeLabel: 'Modo',
    intervalLabel: 'Intervalo (minutos)',
    daysBackLabel: 'Dias retroativos',
    saveSuccess: 'Configurações salvas!',
    modeOptions: {
      FULL: 'Completo',
      DELTA: 'Delta',
      DELTA_WINDOW: 'Delta por janela',
    },
    appearance: {
      title: '🎨 Aparência',
      themeLabel: 'Tema do sistema',
      themeDescription: 'Personalize a aparência do sistema de acordo com sua preferência.',
      light: 'Claro',
      dark: 'Escuro',
      toggleAria: 'Alternar tema do sistema',
    },
  },
  login: {
    title: 'KB Governance',
    subtitle: 'Faça login para continuar',
    logoAlt: 'Consisa Sistemas',
    emailLabel: 'E-mail',
    emailPlaceholder: 'seu@email.com',
    passwordLabel: 'Senha',
    passwordPlaceholder: '••••••••',
    submit: 'Entrar',
    submitting: 'Entrando...',
    success: 'Login realizado com sucesso!',
    errorTitle: 'Erro',
    demo: 'Use suas credenciais Consisa. Em DEV pode existir demo via .env.',
  },
  notFound: {
    title: '404',
    description: 'Página não encontrada',
    backHome: 'Voltar para o início',
    logMessage: 'Erro 404: rota inexistente acessada',
  },
  index: {
    title: 'Bem-vindo à governança',
    description: 'Acesse o menu lateral para começar.',
  },
  navigation: {
    appTitle: 'Consisa / KB Governance',
    routes: {
      dashboard: 'Painel',
      articles: 'Manuais',
      governance: 'Governança',
      needs: 'Necessidades',
      responsibles: 'Responsáveis',
      workload: 'Carga do time',
      sync: 'Sincronização',
      settings: 'Configurações',
    },
    sidebar: {
      brandAria: 'Consisa Sistemas - KB Governance',
      brandTitle: 'Consisa Sistemas',
      expand: 'Expandir menu',
      collapse: 'Recolher menu',
      logout: 'Sair',
    },
    topbar: {
      notifications: 'Notificações',
      userMenu: 'Menu do usuário',
      defaultUser: 'Usuário',
      profile: 'Perfil',
      preferences: 'Preferências',
      logout: 'Sair',
    },
  },
  governance: {
    title: 'Governança',
    description: 'O que precisa ser feito, por quem e até quando',
    filtersTitle: 'Filtros para gestão',
    filters: {
      type: 'Tipo de pendência',
      typePlaceholder: 'Todos os tipos',
      severity: 'Impacto',
      severityPlaceholder: 'Todos os impactos',
      system: 'Sistema',
      systemPlaceholder: 'Todos os sistemas',
      status: 'Situação',
      statusPlaceholder: 'Todas as situações',
      search: 'Busca',
      searchPlaceholder: 'Buscar por resumo ou manual',
      responsible: 'Responsável',
      responsiblePlaceholder: 'Filtrar por responsável',
      overdue: 'Somente vencidas',
      unassigned: 'Sem responsável',
      criticalOnly: 'Somente críticas',
    },
    summary: {
      openTotal: 'Pendências em aberto',
      errorOpen: 'Críticas',
      unassignedOpen: 'Sem responsável',
      overdueOpen: 'Atrasadas',
      empty: 'Indicadores indisponíveis no momento.',
      loadError: 'Erro ao carregar indicadores',
    },
    systems: {
      title: 'Saúde por sistema',
      subtitle: 'Clique em um sistema para filtrar a fila.',
      emptyTitle: 'Nenhum sistema encontrado',
      emptyDescription: 'Assim que houver dados por sistema, eles aparecem aqui.',
      loadError: 'Erro ao carregar sistemas',
      table: {
        system: 'Sistema',
        healthScore: 'Saúde do sistema',
        open: 'Pendências em aberto',
        critical: 'Críticas',
        overdue: 'Atrasadas',
        unassigned: 'Sem responsável',
      },
    },
    list: {
      title: 'Fila de pendências',
      count: (total: number) => `${total} pendência${total !== 1 ? 's' : ''}`,
      loadError: 'Erro ao carregar pendências',
      emptyTitle: 'Nenhuma pendência encontrada',
      emptyDescription: 'Ajuste os filtros para visualizar as pendências pendentes.',
      table: {
        issue: 'O que está errado?',
        situation: 'Situação',
        severity: 'Quão grave é?',
        responsible: 'Quem resolve?',
        overdue: 'Está atrasado?',
        actions: 'Ações rápidas',
      },
      actionAssign: 'Atribuir',
      actionStatus: 'Resolver / ignorar',
      actionDueDate: 'Ajustar prazo',
      actionDetail: 'Detalhe',
    },
    statusDialog: {
      title: 'Atualizar situação da pendência',
      statusLabel: 'Situação',
      statusPlaceholder: 'Selecione a situação',
      ignoredReasonLabel: 'Motivo obrigatório',
      ignoredReasonPlaceholder: 'Descreva o motivo para descartar',
      cancel: 'Cancelar',
      save: 'Atualizar situação',
      saving: 'Salvando...',
      ignoredReasonRequired: 'Informe o motivo para descartar a pendência.',
      success: 'Situação atualizada com sucesso.',
    },
    assignDialog: {
      title: 'Atribuir responsável',
      suggestionTitle: 'Sugestão automática',
      suggestionLoading: 'Buscando responsável recomendado...',
      suggestionEmpty: 'Nenhuma sugestão encontrada.',
      alternativesTitle: 'Alternativas',
      assignTo: (name: string) => `Atribuir para ${name}`,
      responsibleLabel: 'Responsável (nome)',
      responsiblePlaceholder: 'Informe o nome do responsável',
      responsibleTypeLabel: 'Tipo de responsável',
      responsibleTypePlaceholder: 'Selecione o tipo',
      responsibleTypeOptions: {
        USER: 'Usuário',
        TEAM: 'Time',
        ROLE: 'Papel',
      },
      responsibleIdLabel: 'Identificador do responsável',
      responsibleIdPlaceholder: 'Informe o ID ou e-mail do responsável',
      dueDateLabel: 'Prazo',
      quickDateToday: 'Hoje',
      quickDateThreeDays: '+3 dias',
      quickDateSevenDays: '+7 dias',
      cancel: 'Cancelar',
      save: 'Salvar atribuição',
      saveWithTicket: 'Atribuir e abrir ticket',
      saving: 'Salvando...',
      missingResponsibleId: 'Informe o identificador do responsável para atribuição.',
      success: 'Responsável atribuído com sucesso.',
    },
    toasts: {
      loadError: 'Erro ao carregar pendências',
      assignError: 'Erro ao atribuir responsável',
      statusError: 'Erro ao atualizar situação',
      suggestionError: 'Erro ao carregar sugestão',
    },
    statusLabels: {
      overdue: 'Atrasado',
      dueToday: 'Vence hoje',
      onTrack: 'No prazo',
      noDueDate: 'Sem prazo',
    },
  },
  issueDetail: {
    title: 'Detalhe da pendência',
    description: 'Entenda o contexto, prazos e histórico',
    backToList: 'Voltar para governança',
    loadError: 'Erro ao carregar detalhes da pendência',
    historyError: 'Erro ao carregar histórico',
    unauthorizedTitle: 'Pendência restrita',
    unauthorizedDescription: 'Você só pode visualizar pendências atribuídas ao seu usuário.',
    notFoundTitle: 'Pendência não encontrada',
    notFoundDescription: 'Verifique o link ou volte para a governança para selecionar outra pendência.',
    typeLabel: 'Tipo',
    systemLabel: 'Sistema',
    manualLabel: 'Manual',
    impactLabel: 'Impacto',
    statusLabel: 'Situação',
    responsibleLabel: 'Responsável',
    dueDateLabel: 'Prazo',
    dueDatePrefix: 'Vence em',
    slaDaysPrefix: 'Prazo estimado:',
    daysLabel: 'dias',
    createdAtLabel: 'Criada em',
    summaryTitle: 'Resumo do que está errado',
    whatIsItTitle: 'O que está errado',
    howToResolveTitle: 'Como resolver',
    noDescription: 'Descrição indisponível no momento.',
    noRecommendation: 'Recomendação indisponível no momento.',
    metadataTitle: 'Dados da pendência',
    historyTitle: 'Histórico de atualizações',
    historyLoading: 'Carregando histórico...',
    historyEmptyTitle: 'Nenhum histórico encontrado',
    historyEmptyDescription: 'Ainda não há alterações registradas para essa pendência.',
    changedByLabel: 'por',
    updateLabel: 'Atualização',
    duplicatesTitle: 'Duplicidades',
    duplicatesHashLabel: 'Hash',
    duplicatesEmpty: 'Nenhuma duplicidade encontrada.',
    viewManual: 'Abrir manual',
    updatedAtLabel: 'Atualizado em',
    unavailableUrl: 'Link indisponível',
  },
  responsibles: {
    title: 'Responsáveis',
    description: 'Carga operacional por responsável',
    loadError: 'Erro ao carregar responsáveis',
    summary: {
      totalResponsibles: 'Total de responsáveis',
      openPending: 'Pendências em aberto',
      overdue: 'Pendências atrasadas',
    },
    table: {
      title: 'Resumo por responsável',
      emptyTitle: 'Nenhum responsável encontrado',
      emptyDescription: 'Assim que houver responsáveis atribuídos, eles aparecem aqui.',
      headers: {
        responsible: 'Responsável',
        open: 'Pendências em aberto',
        overdue: 'Atrasadas',
        averageSla: 'Tempo médio',
        actions: 'Ações',
      },
      actions: {
        backlog: 'Ver backlog',
        quickAssign: 'Atribuir rápido',
      },
      days: (value: number) => `${value.toFixed(1)} dias`,
    },
  },
  workload: {
    title: 'Carga do time',
    description: 'Visão simples da distribuição de pendências por pessoa',
    emptyTitle: 'Sem responsáveis com pendências',
    emptyDescription: 'Assim que houver pendências atribuídas, elas aparecerão aqui.',
    loadError: 'Erro ao carregar a carga do time',
    table: {
      headers: {
        responsible: 'Pessoa',
        open: 'Issues abertas',
        overdue: 'Issues vencidas',
        systems: 'Sistemas que atua',
      },
    },
  },
  needs: {
    title: 'Necessidades',
    description: 'Priorize o que precisa ser produzido ou revisado',
    filtersTitle: 'Filtros para gestão',
    filters: {
      system: 'Sistema',
      systemPlaceholder: 'Todos os sistemas',
      status: 'Situação',
      statusPlaceholder: 'Todas as situações',
      severity: 'Impacto',
      severityPlaceholder: 'Todos os impactos',
      startDate: 'Início',
      endDate: 'Fim',
      sort: 'Ordenação',
      sortPlaceholder: 'Ordenar por',
      sortOptions: {
        impact: 'Maior impacto',
        recurrence: 'Mais recorrente',
      },
    },
    list: {
      title: 'Fila de necessidades',
      emptyTitle: 'Nenhuma necessidade encontrada',
      emptyDescription: 'Ajuste os filtros para visualizar as necessidades pendentes.',
      windowLabel: 'Janela',
      quantityLabel: 'Quantidade',
      occurrencesLabel: 'Ocorrências',
      lastOccurrenceLabel: 'Última ocorrência',
      reasonLabel: 'Motivo',
      actionsLabel: 'Ações',
      noWindow: 'Sem janela definida',
      noReason: 'Motivo não informado',
      linkLabel: 'Abrir link',
    },
    detail: {
      title: 'Detalhe da necessidade',
      loading: 'Carregando informações...',
      error: 'Erro ao carregar detalhe',
      createdAtLabel: 'Gerado em',
      reasonTitle: 'Por que foi gerado',
      noReason: 'Motivo não informado pelo backend.',
      examplesTitle: 'Exemplos de tickets',
      noExampleTitle: 'Ticket sem título',
      openedAtLabel: 'Aberto em',
      viewTicket: 'Abrir ticket',
      noExamples: 'Nenhum exemplo retornado pelo backend.',
      selectPrompt: 'Selecione uma necessidade para ver detalhes.',
      taskSuccess: 'Tarefa criada',
      taskDescription: 'A tarefa interna foi registrada com sucesso.',
      ticketSuccess: 'Ticket mestre criado',
      ticketDescription: 'O ticket mestre foi registrado com sucesso.',
    },
    actions: {
      createTask: 'Criar tarefa interna',
      createTicket: 'Criar ticket mestre',
      confirmTitle: 'Confirmar ação',
      confirmTask: 'Deseja criar uma tarefa interna para esta necessidade?',
      confirmTicket: 'Deseja criar um ticket mestre para esta necessidade?',
      processing: 'Processando...',
      confirm: 'Confirmar',
    },
    errors: {
      loadNeeds: 'Erro ao carregar necessidades',
      actionError: 'Erro ao executar ação',
    },
  },
  statusBadge: {
    labels: {
      OK: 'Em dia',
      WARNING: 'Atenção',
      PENDING: 'Pendente',
      SYNCED: 'Sincronizado',
      OUTDATED: 'Desatualizado',
      FAILED: 'Falhou',
      OPEN: 'Aguardando ação',
      ASSIGNED: 'Com responsável',
      IN_PROGRESS: 'Em andamento',
      RESOLVED: 'Resolvido',
      IGNORED: 'Descartado',
      INFO: 'Informativo',
      WARN: 'Alerta',
      ERROR: 'Crítico',
      RUNNING: 'Executando',
      COMPLETED: 'Concluído',
      CANCELLED: 'Cancelado',
    },
  },
} as const;
